"""add ondelete cascade

Revision ID: e4b1f7075b92
Revises: 0240d6c0e1d2
Create Date: 2023-05-31 22:56:50.278245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b1f7075b92'
down_revision = '0240d6c0e1d2'
branch_labels = None
depends_on = None

naming_convention = {
    "fk":
    "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channelmembers', naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_channelmembers_member_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_channelmembers_channel_id_channels', type_='foreignkey')
        batch_op.create_foreign_key('fk_channelmembers_member_id_users', 'users', ['member_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_channelmembers_channel_id_channels', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('channels', naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_channels_server_id_servers', type_='foreignkey')
        batch_op.create_foreign_key('fk_channels_server_id_servers', 'servers', ['server_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('messages', naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_messages_channel_id_channels', type_='foreignkey')
        batch_op.drop_constraint('fk_messages_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key('fk_messages_channel_id_channels', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_messages_user_id_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('servermembers', naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_servermembers_member_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_servermembers_server_id_servers', type_='foreignkey')
        batch_op.create_foreign_key('fk_servermembers_member_id_users', 'users', ['member_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_servermembers_server_id_servers', 'servers', ['server_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('servers', naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_servers_owner_id_users', type_='foreignkey')
        batch_op.create_foreign_key('fk_servers_owner_id_users', 'users', ['owner_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_servers_owner_id_users', type_='foreignkey')
        batch_op.create_foreign_key('fk_servers_owner_id_users', 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('servermembers', naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_servermembers_server_id_servers', type_='foreignkey')
        batch_op.drop_constraint('fk_servermembers_member_id_users', type_='foreignkey')
        batch_op.create_foreign_key('fk_servermembers_server_id_servers', 'servers', ['server_id'], ['id'])
        batch_op.create_foreign_key('fk_servermembers_member_id_users', 'users', ['member_id'], ['id'])

    with op.batch_alter_table('messages', naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_messages_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_messages_channel_id_channels', type_='foreignkey')
        batch_op.create_foreign_key('fk_messages_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_messages_channel_id_channels', 'channels', ['channel_id'], ['id'])

    with op.batch_alter_table('channels', naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_channels_server_id_servers', type_='foreignkey')
        batch_op.create_foreign_key('fk_channels_server_id_servers', 'servers', ['server_id'], ['id'])

    with op.batch_alter_table('channelmembers', naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_channelmembers_channel_id_channels', type_='foreignkey')
        batch_op.drop_constraint('fk_channelmembers_member_id_users', type_='foreignkey')
        batch_op.create_foreign_key('fk_channelmembers_channel_id_channels', 'channels', ['channel_id'], ['id'])
        batch_op.create_foreign_key('fk_channelmembers_member_id_users', 'users', ['member_id'], ['id'])

    # ### end Alembic commands ###
